# @package _global_

model:
  decoder_params:
    layers_per_block_per_layer: [2,2,2,2,2,2,2,2]
    channel_size_per_layer: [256,256,128,128,128,128,64,64]
    num_layers_per_resolution: [2,2,2,2]
  encoder_params:
    layers_per_block_per_layer: [2,2,2,2,2,2,2,2]
    downsample: 3
    channel_size_per_layer: [64,64,128,128,128,128,256,256]
    num_layers_per_resolution: [2,2,2,2]