# @package _global_

model:
  num_slots: ${dataset.max_num_objects}
  latent_size: 64
  encoder_params:
    channels: [32, 32, 32, 32]
    kernels: [5, 5, 5, 5]
    paddings: [2, 2, 2, 2]
    strides: [1, 1, 1, 1]
  decoder_params:
    conv_transposes: false
    channels: [32, 32, 32, 4]
    kernels: [5, 5, 5, 3]
    strides: [1, 1, 1, 1]
    paddings: [2, 2, 2, 1]
    output_paddings: [0, 0, 0, 0]
    activations: [relu, relu, relu, null]
  attention_iters: 3
  optimization_method: "bi-level"
  slots_initialization: "embedding"
  mlp_size: 128
  eps: 1e-8
  h_broadcast: ${dataset.height}
  w_broadcast: ${dataset.width}
