# @package _global_

batch_size: 64
model:
  num_slots: &num_slots 4
  model_params:
    temps: [1.00, 2.00]
    channels: [1, 64, 64]
    num_attns: [2, 2]
    attn_q_kernels: [4, 8]
    attn_k_kernels: [4, 8]
    attn_q_strides: [4, 1]
    attn_k_strides: [4, 1]
    attn_q_paddings: [0, 0]
    attn_k_paddings: [0, 0]
    num_clusters: [1, 3, *num_slots]
    kernels: [[1,1], [4,4], [8,8]]
    strides: [[1,1], [4,4], [1,1]] 
    paddings: [[0,0], [0,0], [0,0]]  
  encoder_params:
    channels: 64
    kernel_size: 3
    stride: 1
    padding: 1
    output_channels: 64
  decoder_params:
    conv_transposes: false
    channels: [32, 32, 32, 4]
    kernels: [5, 5, 5, 3]
    strides: [1, 1, 1, 1]
    paddings: [2, 2, 2, 1]
    output_paddings: [0, 0, 0, 0]
    activations: [relu, relu, relu, null]
  h_broadcast: 32
  w_broadcast: 32


